[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
trident_mre = "GAZqgqhqjS6cCnHt8TSC2cceG3vs5MMWppwghMBsUhjF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

anchor_version = "0.30.0-b76d1bf"